# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from main import *
from PyQt5.QtWidgets import QMessageBox
from messages import *

class Ui_MainWindow(object):
    def lateral_load(self):
        global lateral_path
        lateral_path = file()

    def up_load(self):
        global up_path
        up_path = file()

    def hsv(self):
        try:
            lateral_path
            up_path
        except NameError:
            warn1()
        else:
            mode = 2

            # Registro de los valores del limite inferior
            h_low = self.low_h.text()
            s_low = self.low_s.text()
            v_low = self.low_v.text()

            # Registro de los valores del limite superior
            h_high = self.high_h.text()
            s_high = self.high_s.text()
            v_high = self.high_v.text()

            hsv_list = [h_low, s_low, v_low, h_high, s_high, v_high]

            ver = verify(hsv_list, 0, mode)

            if ver == 0:
                hsv_low = (int(h_low), int(s_low), int(v_low))
                hsv_high = (int(h_high), int(s_high), int(v_high))

                output = main(lateral_path, up_path, hsv_low, hsv_high)

                img1 = QPixmap(output[0])
                img2 = QPixmap(output[1])

                img1 = img1.scaled(408, 225, aspectRatioMode=QtCore.Qt.KeepAspectRatio,
                                   transformMode=QtCore.Qt.SmoothTransformation)
                img2 = img2.scaled(408, 225, aspectRatioMode=QtCore.Qt.KeepAspectRatio,
                                   transformMode=QtCore.Qt.SmoothTransformation)
                self.up_frame.setPixmap(img1)
                self.lateral_frame.setPixmap(img2)
                self.decision.setText(str(output[2]))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 732)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 801, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 20, 251, 371))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_8)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 231, 331))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 3, 0, 1, 1)
        self.high_h = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.high_h.setAlignment(QtCore.Qt.AlignCenter)
        self.high_h.setObjectName("high_h")
        self.gridLayout_5.addWidget(self.high_h, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.low_v = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.low_v.setAlignment(QtCore.Qt.AlignCenter)
        self.low_v.setObjectName("low_v")
        self.gridLayout_5.addWidget(self.low_v, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.low_h = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.low_h.setAlignment(QtCore.Qt.AlignCenter)
        self.low_h.setObjectName("low_h")
        self.gridLayout_5.addWidget(self.low_h, 1, 1, 1, 1)
        self.low_s = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.low_s.setAlignment(QtCore.Qt.AlignCenter)
        self.low_s.setObjectName("low_s")
        self.gridLayout_5.addWidget(self.low_s, 2, 1, 1, 1)
        self.high_s = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.high_s.setAlignment(QtCore.Qt.AlignCenter)
        self.high_s.setObjectName("high_s")
        self.gridLayout_5.addWidget(self.high_s, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 7, 0, 1, 1)
        self.high_v = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.high_v.setAlignment(QtCore.Qt.AlignCenter)
        self.high_v.setObjectName("high_v")
        self.gridLayout_5.addWidget(self.high_v, 7, 1, 1, 1)
        self.lateral_video = QtWidgets.QPushButton(self.tab)
        self.lateral_video.setGeometry(QtCore.QRect(10, 420, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.lateral_video.setFont(font)
        self.lateral_video.setObjectName("lateral_video")
        self.up_video = QtWidgets.QPushButton(self.tab)
        self.up_video.setGeometry(QtCore.QRect(10, 480, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.up_video.setFont(font)
        self.up_video.setObjectName("up_video")
        self.start = QtWidgets.QPushButton(self.tab)
        self.start.setGeometry(QtCore.QRect(60, 540, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.groupBox_28 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_28.setGeometry(QtCore.QRect(280, 30, 500, 260))
        self.groupBox_28.setObjectName("groupBox_28")
        self.up_frame = QtWidgets.QLabel(self.groupBox_28)
        self.up_frame.setGeometry(QtCore.QRect(50, 30, 409, 230))
        self.up_frame.setText("")
        self.up_frame.setObjectName("up_frame")
        self.groupBox_29 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_29.setGeometry(QtCore.QRect(280, 300, 500, 260))
        self.groupBox_29.setObjectName("groupBox_29")
        self.lateral_frame = QtWidgets.QLabel(self.groupBox_29)
        self.lateral_frame.setGeometry(QtCore.QRect(50, 30, 409, 230))
        self.lateral_frame.setText("")
        self.lateral_frame.setObjectName("lateral_frame")
        self.groupBox_30 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_30.setGeometry(QtCore.QRect(390, 560, 231, 101))
        self.groupBox_30.setObjectName("groupBox_30")
        self.decision = QtWidgets.QLabel(self.groupBox_30)
        self.decision.setGeometry(QtCore.QRect(10, 40, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.decision.setFont(font)
        self.decision.setText("")
        self.decision.setAlignment(QtCore.Qt.AlignCenter)
        self.decision.setObjectName("decision")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 0, 781, 611))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        # Asigning functions to buttons in one code block
        self.lateral_video.clicked.connect(self.lateral_load)
        self.up_video.clicked.connect(self.up_load)
        self.start.clicked.connect(self.hsv)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Short Serve Prototype"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Parameters"))
        self.label_9.setText(_translate("MainWindow", "V value:"))
        self.label_6.setText(_translate("MainWindow", "H value:"))
        self.label_11.setText(_translate("MainWindow", "S value:"))
        self.label_26.setText(_translate("MainWindow", "High limit:"))
        self.label_7.setText(_translate("MainWindow", "S value:"))
        self.label_10.setText(_translate("MainWindow", "H value:"))
        self.label_13.setText(_translate("MainWindow", "Low limit:"))
        self.label_12.setText(_translate("MainWindow", "V value:"))
        self.lateral_video.setText(_translate("MainWindow", "Load Lateral Video"))
        self.up_video.setText(_translate("MainWindow", "Load Up Video"))
        self.start.setText(_translate("MainWindow", "START"))
        self.groupBox_28.setTitle(_translate("MainWindow", "Up frame"))
        self.groupBox_29.setTitle(_translate("MainWindow", "Lateral frame"))
        self.groupBox_30.setTitle(_translate("MainWindow", "Decision"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\">Prototype software developed as part of the requirements for achieving </p><p align=\"center\">the Mechanical Engineering Degree of the Universidad del Atlántico by: <br/></p><p align=\"center\">Diego Balanta García </p><p align=\"center\">dbalanta@mail.uniatlantico.edu.co </p><p align=\"center\">Diego Palomino Rodríguez </p><p align=\"center\">dpalomino@mail.uniatlantico.edu.co <br/></p><p align=\"center\">Project Director: PhD. Ing. Mec. Javier Roldán Mckinley. <br/></p><p align=\"center\">Property of Universidad del Atlántico. </p><p align=\"center\">Barranquilla, Colombia.</p><p align=\"center\">2022</p><p align=\"center\">All rights reserved.</p><p align=\"center\"><br/></p><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
